### ISSUE TITLE
v2rayn客户端 中ssl无法匹配

### ISSUE THREAD

**Issue by Hylloe** [zydou/GFW#1]
您好，先生。根据您的naiveproxy的docker-compose.yml的配置，最后一行，您写的https://user..........,但是根据您的内容可以在服务器上正常运行，拉取docker镜像。但是naive节点要ssl证书呀。我提前申请了一个证书，我根据您的文档 进行了一下调整。一下是我的docker compose文档
version: "3.9"
services:
  service.naiveproxy:
    image: zydou/naiveproxy:latest
    container_name: naiveproxy
    ports:
      - 4221:1080
    restart: always

    volumes:
      - /home/naiveproxy/cert/fullchain.pem/:/etc/naiveproxy/fullchain.pem:ro
      - /home/naiveproxy/cert/private.pem/:/etc/naiveproxy/private.pem:ro
    command: naive --listen=socks://0.0.0.0:1080 --proxy=https://wangzai:kf4tacqn9e@alihk.niceboy.cfd 。我重新调改的文件可以拉取您的docker镜像。但是无法再客户端正常连接。客户端老是报错ssl错误，我是提前申请了证书的。并在docker  compose中加了一个volumes来映射证书位置。

**Comment by zydou** [comment]
服务器端不需要拉取naiveproxy镜像，需要拉取caddy镜像做server端。naiveproxy镜像是用在本地端的，做客户端使用。

**Comment by zydou** [comment]
在服务器端，可以按如下`docker-compose.yml`文件内容，建立支持naiveproxy的caddy server，同时也支持v2ray。
```yml
version: '3.9'
services:

  # 下面这个服务是支持naiveproxy的caady server端
  # 也可以用来伪装v2ray的websocket流量(vmess+ws+tls 或 vless+ws+tls, 也可以套上CDN)
  service.caddy:
    image: zydou/caddy:naive
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ~/Docker/caddy/Caddyfile:/etc/caddy/Caddyfile  # 修改此Caddyfile内容，和你自己拥有的网站对应上
      - ~/Docker/caddy/sites:/www  # 这里存放一个静态网站做伪装
      - ~/Docker/caddy/data:/data  # 这里面是caddy运行时自己生成的数据，不需要动
      - ~/Docker/caddy/config:/config  # 这里面是caddy自己生成的配置文件，不需要动
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    networks:
      - mydocker_net
    dns:
      - 1.1.1.1
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: 3

  # 下面这个服务是v2ray的server端
  service.v2ray:
    image: zydou/v2ray:v4.45.2
    container_name: v2ray
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ~/Docker/v2ray/config.json:/etc/v2ray/config.json:ro
    networks:
      - mydocker_net
    dns:
      - 1.1.1.1
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: 1
    restart: unless-stopped

  # 下面这个服务是自动更新镜像的，如果不需要自动更新镜像可以删掉这个服务
  # 每个小时自动检查一次镜像是否有更新，如果有的话自动拉取新镜像并重启容器，同时删除旧镜像
  service.watchtower:  
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup --interval 3600 v2ray caddy
    networks:
      - mydocker_net
    dns:
      - 1.1.1.1
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: 1

networks:
  mydocker_net:
```
