### ISSUE TITLE
Use case examples for docker images

### ISSUE THREAD

**Issue by mhmatthewhugley** [zydou/GFW#2]
It would be very helpful if a simple use case or multiple are described for the different docker images.
Such as the "https://github.com/zydou/GFW/blob/master/nextdns/README.md" mentioning it can be used to run other docker containers via NextDNS, or so you can send internal network clients to the docker container instead of directly out of the network.
Or some quick text that describes why someone might want to use the docker container over other methods.

**Comment by mhmatthewhugley** [comment]
Most important spot would be the publicly facing docker hub page which seems to show up before this github page. https://hub.docker.com/r/zydou/nextdns

**Comment by zydou** [comment]
> It would be very helpful if a simple use case or multiple are described for the different docker images. Such as the "https://github.com/zydou/GFW/blob/master/nextdns/README.md" mentioning it can be used to run other docker containers via NextDNS, or so you can send internal network clients to the docker container instead of directly out of the network. Or some quick text that describes why someone might want to use the docker container over other methods.

You can use other services together with NextDNS. For example:

```yaml
version: '3.9'
services:
  service.nextdns:
    image: zydou/nextdns:latest
    container_name: nextdns
    networks:
      mydocker_net:
        ipv4_address: 172.19.0.53
    environment:
      - NEXTDNS_ID=abcdef
      - NEXTDNS_ARGUMENTS=-listen :5353 -report-client-info -log-queries -cache-size 10MB -max-ttl 5s
    ports:
      - 53:5353/udp
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: 1
    restart: unless-stopped

  service.v2ray:
    image: zydou/v2ray:v4.45.2
    container_name: v2ray
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ~/Docker/v2ray/config.json:/etc/v2ray/config.json:ro
    networks:
      - mydocker_net
    dns:
      - 172.19.0.53
    logging:
      driver: json-file
      options:
        max-size: 200k
        max-file: 1
    restart: unless-stopped

networks:
  mydocker_net:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
```

In the example above, the `v2ray` service will utilize NextDNS as its DNS server. This offers the advantage of being able to block ads and trackers using NextDNS. Additionally, NextDNS can be used for making DoH or DoT queries, which is highly beneficial for enhancing security and privacy.
